### ISSUE TITLE
 Error in solve_armadillo(D0) : inv(): matrix is singular #11 

### ISSUE THREAD

**Issue by fl0rianB** [joaomacalos/sfcr#4]
Hi,
I get an error that I don't understand when I use large numbers (Gd ~ 2e+10 in the example below), any idea why this is happening? Thanks!

`
library(sfcr)

sim_eqs <- sfcr_set(
TXs ~ TXd,
YD ~ W * Ns - TXs,
Cd ~ alpha1 * YD + alpha2 * Hh[-1],
Hh ~ YD - Cd + Hh[-1],
Ns ~ Nd,
Nd ~ Y / W,
Cs ~ Cd,
Gs ~ Gd,
Y ~ Cs + Gs,
TXd ~ theta * W * Ns,
Hs ~ Gd - TXd + Hs[-1]
)

sim_ext <- sfcr_set(
Gd ~ 2e+10, # Large number here
W ~ 1,
alpha1 ~ 0.6,
alpha2 ~ 0.4,
theta ~ 0.2
)

system.time(sim <- sfcr_baseline(
equations = sim_eqs,
external = sim_ext,
periods = 100,
hidden = c("Hh" = "Hs"),
method = "Broyden")
)`

**Comment by joaomacalos** [comment]
Hi,

The algorithms work by slicing the system of equations into blocks of equations that depend on each other and iterating with the solvers to find a solution. In the case of the Broyden solver, it needs to invert a Jacobian matrix of the variables in this block. This mistake is saying that the Jacobian matrix that the `solve_armadillo` function is trying to invert is singular and cannot be inverted. Most likely the model is "exploding", i.e., some of the values are quickly converging to `Inf`. The same error may arise in more complicated models, and the solution is to find an appropriate set of initial values (i.e., calibrate the model). 

Try to run the model with fewer periods (say 2, 3) and inspect the trajectory of the model. It's also always a good idea to try the `Newton` solver as well.

In this example, you supply a value that is very large for Gd, that immediately defines Gs, while the remaining variables are initialized at values that are very close to zero. Most likely you will have to set different initial values to be consistent with the very large Gd value that you are supplying.

**Comment by fl0rianB** [comment]
Ok, thanks a lot for your help and your great work!
Best
